import 'dart:math';

class Data {
  final String english;
  final String thai;
  final String filePath;

  Data({
    required this.english,
    required this.thai,
    required this.filePath,
  });
}

final List<Data> words = [
  Data(english: "cat", thai: "แมว", filePath: "assets/images/cat.jpg"),
  Data(english: "dog", thai: "หมา", filePath: "assets/images/dog.jpg"),
  Data(english: "apple", thai: "แอปเปิล", filePath: "assets/images/apple.jpg"),
  Data(english: "ball", thai: "ลูกบอล", filePath: "assets/images/ball.jpg"),
  Data(english: "bird", thai: "นก", filePath: "assets/images/bird.jpg"),
  Data(english: "book", thai: "หนังสือ", filePath: "assets/images/book.jpg"),
  Data(english: "boy", thai: "เด็กผู้ชาย", filePath: "assets/images/boy.jpg"),
  Data(english: "girl", thai: "เด็กผู้หญิง", filePath: "assets/images/girl.jpg"),
  Data(english: "car", thai: "รถยนต์", filePath: "assets/images/car.jpg"),
  Data(english: "bus", thai: "รถบัส", filePath: "assets/images/bus.jpg"),
  Data(english: "cup", thai: "ถ้วย", filePath: "assets/images/cup.jpg"),
  Data(english: "door", thai: "ประตู", filePath: "assets/images/door.jpg"),
  Data(english: "egg", thai: "ไข่", filePath: "assets/images/egg.jpg"),
  Data(english: "fish", thai: "ปลา", filePath: "assets/images/fish.jpg"),
  Data(english: "frog", thai: "กบ", filePath: "assets/images/frog.jpg"),
  Data(english: "goat", thai: "แพะ", filePath: "assets/images/goat.jpg"),
  Data(english: "hat", thai: "หมวก", filePath: "assets/images/hat.jpg"),
  Data(english: "house", thai: "บ้าน", filePath: "assets/images/house.jpg"),
  Data(english: "ice", thai: "น้ำแข็ง", filePath: "assets/images/ice.jpg"),
  Data(english: "juice", thai: "น้ำผลไม้", filePath: "assets/images/juice.jpg"),
  Data(english: "kite", thai: "ว่าว", filePath: "assets/images/kite.jpg"),
  Data(english: "lion", thai: "สิงโต", filePath: "assets/images/lion.jpg"),
  Data(english: "milk", thai: "นม", filePath: "assets/images/milk.jpg"),
  Data(english: "moon", thai: "ดวงจันทร์", filePath: "assets/images/moon.jpg"),
  Data(english: "nose", thai: "จมูก", filePath: "assets/images/nose.jpg"),
  Data(english: "orange", thai: "ส้ม", filePath: "assets/images/orange.jpg"),
  Data(english: "pen", thai: "ปากกา", filePath: "assets/images/pen.jpg"),
  Data(english: "pig", thai: "หมู", filePath: "assets/images/pig.jpg"),
  Data(english: "queen", thai: "ราชินี", filePath: "assets/images/queen.jpg"),
  Data(english: "rain", thai: "ฝน", filePath: "assets/images/rain.jpg"),
  Data(english: "rice", thai: "ข้าว", filePath: "assets/images/rice.jpg"),
  Data(english: "sun", thai: "ดวงอาทิตย์", filePath: "assets/images/sun.jpg"),
  Data(english: "star", thai: "ดาว", filePath: "assets/images/star.jpg"),
  Data(english: "tree", thai: "ต้นไม้", filePath: "assets/images/tree.jpg"),
  Data(english: "toy", thai: "ของเล่น", filePath: "assets/images/toy.jpg"),
  Data(english: "umbrella", thai: "ร่ม", filePath: "assets/images/umbrella.jpg"),
  Data(english: "van", thai: "รถตู้", filePath: "assets/images/van.jpg"),
  Data(english: "water", thai: "น้ำ", filePath: "assets/images/water.jpg"),
  Data(english: "window", thai: "หน้าต่าง", filePath: "assets/images/window.jpg"),
  Data(english: "zoo", thai: "สวนสัตว์", filePath: "assets/images/zoo.jpg"),
  Data(english: "ant", thai: "มด", filePath: "assets/images/ant.jpg"),
  Data(english: "bear", thai: "หมี", filePath: "assets/images/bear.jpg"),
  Data(english: "cake", thai: "เค้ก", filePath: "assets/images/cake.jpg"),
  Data(english: "duck", thai: "เป็ด", filePath: "assets/images/duck.jpg"),
  Data(english: "elephant", thai: "ช้าง", filePath: "assets/images/elephant.jpg"),
  Data(english: "flower", thai: "ดอกไม้", filePath: "assets/images/flower.jpg"),
  Data(english: "hand", thai: "มือ", filePath: "assets/images/hand.jpg"),
  Data(english: "key", thai: "กุญแจ", filePath: "assets/images/key.jpg"),
  Data(english: "lamp", thai: "โคมไฟ", filePath: "assets/images/lamp.jpg"),
  Data(english: "monkey", thai: "ลิง", filePath: "assets/images/monkey.jpg"),
  Data(english: "owl", thai: "นกฮูก", filePath: "assets/images/owl.jpg"),
  Data(english: "snake", thai: "งู", filePath: "assets/images/snake.jpg"),
  // Data(english: "grape", thai: "องุ่น", filePath: "g"),
  // Data(english: "island", thai: "เกาะ", filePath: "i"),
  // Data(english: "jacket", thai: "เสื้อแจ็คเก็ต", filePath: "j"),
  // Data(english: "nest", thai: "รัง", filePath: "n"),
  // Data(english: "panda", thai: "แพนด้า", filePath: "p"),
  // Data(english: "queen", thai: "ราชินี", filePath: "q"),
  // Data(english: "road", thai: "ถนน", filePath: "r"),
  // Data(english: "table", thai: "โต๊ะ", filePath: "t"),
  // Data(english: "unit", thai: "หน่วย", filePath: "u"),
  // Data(english: "vase", thai: "แจกัน", filePath: "v"),
  // Data(english: "wolf", thai: "หมาป่า", filePath: "w"),
  // Data(english: "box", thai: "กล่อง", filePath: "b"),
  // Data(english: "chair", thai: "เก้าอี้", filePath: "c"),
  // Data(english: "desk", thai: "โต๊ะทำงาน", filePath: "d"),
  // Data(english: "ear", thai: "หู", filePath: "e"),
  // Data(english: "face", thai: "หน้า", filePath: "f"),
  // Data(english: "glass", thai: "แก้ว", filePath: "g"),
  // Data(english: "hill", thai: "เนินเขา", filePath: "h"),
  // Data(english: "ink", thai: "หมึก", filePath: "i"),
  // Data(english: "jam", thai: "แยม", filePath: "j"),
  // Data(english: "knife", thai: "มีด", filePath: "k"),
  // Data(english: "leaf", thai: "ใบไม้", filePath: "l"),
  // Data(english: "map", thai: "แผนที่", filePath: "m"),
  // Data(english: "net", thai: "ตาข่าย", filePath: "n"),
  // Data(english: "oil", thai: "น้ำมัน", filePath: "o"),
  // Data(english: "park", thai: "สวนสาธารณะ", filePath: "p"),
  // Data(english: "quiz", thai: "แบบทดสอบ", filePath: "q"),
  // Data(english: "river", thai: "แม่น้ำ", filePath: "r"),
  // Data(english: "ship", thai: "เรือ", filePath: "s"),
  // Data(english: "train", thai: "รถไฟ", filePath: "t"),
  // Data(english: "user", thai: "ผู้ใช้", filePath: "u"),
  // Data(english: "village", thai: "หมู่บ้าน", filePath: "v"),
  // Data(english: "wall", thai: "กำแพง", filePath: "w"),
  // Data(english: "xray", thai: "เอกซเรย์", filePath: "x"),
  // Data(english: "yarn", thai: "ไหมพรม", filePath: "y"),
  // Data(english: "zebra", thai: "ม้าลาย", filePath: "z"),
  // Data(english: "red", thai: "สีแดง", filePath: "r"),
  // Data(english: "blue", thai: "สีน้ำเงิน", filePath: "b"),
  // Data(english: "green", thai: "สีเขียว", filePath: "g"),
  // Data(english: "black", thai: "สีดำ", filePath: "b"),
  // Data(english: "white", thai: "สีขาว", filePath: "w"),
  // Data(english: "one", thai: "หนึ่ง", filePath: "o"),
  // Data(english: "two", thai: "สอง", filePath: "t"),
  // Data(english: "three", thai: "สาม", filePath: "t"),
];

final Random _random = Random();

Data getRandomWord() {
  return words[_random.nextInt(words.length)];
}